[OPENMIND-14] Implement all the repositories
pikulo-kama/openmind pull request #17
Opened 2021-01-16 09:24 UTC by pikulo-kama

2021-01-16 13:16 UTC, MarrMika requested changes
In general good, but we need improvement. Please, fix comments!

2021-01-16 13:16 UTC, MarrMika commented on src/main/java/com/arthurdrabazha/openmind/controller/CategoryController.java
> +}
I see the mess in this class. Delete this one, please.

2021-01-16 13:16 UTC, MarrMika commented on src/main/java/com/arthurdrabazha/openmind/repository/CategoryRepository.java
> +@Repository
It is not necessary to use @Repository annotation here

2021-01-16 13:16 UTC, MarrMika commented on src/main/java/com/arthurdrabazha/openmind/repository/PostRepository.java
> +
Have you checked whether all these methods work correctly?

2021-01-16 16:00 UTC, pikulo-kama commented on src/main/java/com/arthurdrabazha/openmind/controller/CategoryController.java
> +}
Sorry, my mistake. I will delete this one.

2021-01-16 16:01 UTC, pikulo-kama commented on src/main/java/com/arthurdrabazha/openmind/repository/CategoryRepository.java
> +@Repository
But in that case I'll not be able to use repository as bean for injection in my services. Isn't it?

2021-01-18 14:17 UTC, MarrMika commented on src/main/java/com/arthurdrabazha/openmind/repository/CategoryRepository.java
> +@Repository
Nope, you will be able to. It's a specification, not an implementation

2021-01-18 15:21 UTC, MarrMika approved these changes

2021-01-18 15:21 UTC, MarrMika commented on src/main/java/com/arthurdrabazha/openmind/repository/CategoryRepository.java
> +
Why Category PK has a Short type?

2021-01-18 15:37 UTC, pikulo-kama commented on src/main/java/com/arthurdrabazha/openmind/repository/CategoryRepository.java
> +
I think, that will be better, to use type which consumes less space. Anyway, I don't think that count of categories will ever exceed max value of Short.

2021-01-18 15:52 UTC, MarrMika commented on src/main/java/com/arthurdrabazha/openmind/repository/CategoryRepository.java
> +
Please, don't mix between Long and Short. By default, bigint type in PostgreSQL equals 64 bits that is the most appropriate to use Long

2021-01-18 21:20 UTC, pikulo-kama commented on src/main/java/com/arthurdrabazha/openmind/repository/CategoryRepository.java
> +
Okay, I'll keep that in mind. I will change PK type to Long, and then merge thia branch with master

2021-01-20 15:55 UTC, merged