[OPENMIND-19] Implement user service
pikulo-kama/openmind pull request #28
Opened 2021-01-20 17:46 UTC by pikulo-kama

2021-01-22 21:46 UTC, MarrMika requested changes

2021-01-23 18:54 UTC, pikulo-kama commented on pom.xml
> +    </profiles>
It's just the first solution I've found. I will check if I can implement this behaviour using single profile.

2021-01-23 19:06 UTC, pikulo-kama commented on src/main/java/com/arthurdrabazha/openmind/dto/UpdateUserPasswordDto.java
> +
There I decided, to use only constraints which represents SQL constraints such as NULL on models. And use other constraints in DTO's.

2021-01-24 06:58 UTC, MarrMika commented on src/main/java/com/arthurdrabazha/openmind/dto/UpdateUserPasswordDto.java
> +
If you want to get these fields not empty in the request, it is better to use NotBlank

2021-01-24 07:02 UTC, MarrMika commented on pom.xml
> +    </profiles>
At least if you want to use different profiles it can be like dev and test for your case

2021-01-24 11:46 UTC, pikulo-kama commented on src/main/java/com/arthurdrabazha/openmind/model/Category.java
In my opinion that will be better, because NotNull constraint represents SQL constraint. Constraints like NotBlank and others can be applied in DTO's. Correct me if I wrong.

2021-01-26 11:34 UTC, MarrMika commented on src/main/java/com/arthurdrabazha/openmind/model/Category.java
Yep, you are right. By default, hibernate translates the bean validation annotations applied to the entities into the DDL schema metadata. Let it be

2021-01-26 11:39 UTC, MarrMika commented on src/main/java/com/arthurdrabazha/openmind/service/UserServiceImpl.java
> +                .updateDate(Timestamp.valueOf(LocalDateTime.now()))
You can make it by means easier by means of using annotation in a model User which automatically generate date like below
```
    @CreationTimestamp
    private Timestamp createdDate;
```
The same for updatedDate:
```
    @UpdateTimestamp
    private Timestamp updatedDate;
```

2021-01-26 11:43 UTC, MarrMika commented on src/main/java/com/arthurdrabazha/openmind/config/WebConfig.java
>  @ComponentScan
This annotation is optional here

2021-01-28 16:56 UTC, MarrMika approved these changes
Impressive work. Keep it up! 
Rename this PR to 'Implement user management logic'
Also, add screens how it works to the description part
Just a couple of comments. Fix them please and can merge)

2021-01-28 16:56 UTC, MarrMika commented on src/main/java/com/arthurdrabazha/openmind/controller/client/UserController.java
> +
I do believe the correct form is 'persistent'. Just check for yourself for the future.

2021-01-28 16:56 UTC, MarrMika commented on src/main/java/com/arthurdrabazha/openmind/controller/client/UserController.java
> +
@PathVariable Long id -  also works in this case

2021-01-28 16:56 UTC, MarrMika commented on src/main/java/com/arthurdrabazha/openmind/controller/client/UserController.java
> +    }
Is this endpoint open for everyone? If it is, then think over the correctness of this logic.

2021-01-28 16:56 UTC, MarrMika commented on src/main/java/com/arthurdrabazha/openmind/controller/client/UserController.java
> +            createUserDto.setRole(UserRole.ROLE_USER);
Yes, you can take it out into service. It would be better!
Please, use all the time curly braces. It is good practice working with if operator.
```
if(){
smth
}
```

2021-01-28 16:56 UTC, MarrMika commented on src/main/java/com/arthurdrabazha/openmind/model/CommentID.java
> +    private Long author_id;
Don't forget to use java syntax. 'authorId'

2021-01-28 16:56 UTC, MarrMika commented on src/main/java/com/arthurdrabazha/openmind/service/UserServiceImpl.java
> +        }
I do believe that it would be better to check this logic at the level of .ftl but it's up to you

2021-01-28 16:56 UTC, MarrMika commented on src/main/java/com/arthurdrabazha/openmind/service/UserServiceImpl.java
> +    @Override
Why did you use @Transactional annotation over here? It's for multiple transactions with DB, but there is only one here. Am I right?

2021-01-28 16:56 UTC, MarrMika commented on src/main/java/com/arthurdrabazha/openmind/service/UserServiceImpl.java
> +    @Override
The same

2021-01-28 16:56 UTC, MarrMika commented on src/main/java/com/arthurdrabazha/openmind/service/UserServiceImpl.java
> +
Did you think what would be other tables that have relationships with a user? How are you going to manage it?

2021-01-28 16:56 UTC, MarrMika commented on src/main/java/com/arthurdrabazha/openmind/service/UserServiceImpl.java
> +    }
is it for reset of passwords or actually for updates?

2021-01-28 16:56 UTC, MarrMika commented on src/main/java/com/arthurdrabazha/openmind/service/UserServiceImpl.java
> +}
What about making it in another way, because you can have a lot of users and get all the users and filtering them can take too much time.
```
public Boolean isLastAdmin() {
        List<User> users = userRepository.findAllByRole(ROLE_ADMIN);

        if (users.isNotEmpty()){
               return users.size() == 1;
         }

        return false;
    }
```

2021-01-29 00:02 UTC, pikulo-kama commented on src/main/java/com/arthurdrabazha/openmind/controller/client/UserController.java
> +    }
This endpoint accessible only for authenticated users

2021-01-29 00:07 UTC, pikulo-kama commented on src/main/java/com/arthurdrabazha/openmind/service/UserServiceImpl.java
> +
Do you mean I should use cascade delete type, in related objects?

2021-01-29 00:20 UTC, pikulo-kama commented on src/main/java/com/arthurdrabazha/openmind/service/UserServiceImpl.java
> +    }
It's  used for update

2021-01-29 17:00 UTC, MarrMika commented on src/main/java/com/arthurdrabazha/openmind/service/UserServiceImpl.java
> +
I am not sure we need cascade delete, It depends on logic. I will be changed in the next iteration if it needs, for now, let it be

2021-01-30 23:02 UTC, merged